apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketsummary
  version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: marketsummary
  template:
    metadata:
      labels:
        app: marketsummary
        version: {{ .Values.version }}
    spec:
      containers:
      - name: marketsummary
        image: {{ .Values.image }}
        resources:
          requests:
            memory: "512Mi"
            cpu: "4m"
          limits:
            memory: "768Mi"
            cpu: "8m"
        
