{{- if not .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: marketsummary
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: marketsummary
  type: ClusterIP
{{- end }}
